version: '3.8'

services:
  herzens-verbundenheit-web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3010:3010"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3010"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "coolify.managed=true"
      - "coolify.type=application"
      - "coolify.name=herzens-verbundenheit-web"
      - "coolify.description=Herzens Verbundenheit - Paartherapie Website"
